const ActionType = {
  SET_USER: 'SET_USER',
  RESET_USER: 'RESET_USER',
  SET_TOKEN: 'SET_TOKEN',
  RESET_TOKEN: 'RESET_TOKEN',
  REFRESH_PAGE: 'REFRESH_PAGE',
  SET_SOCKET: 'SET_SOCKET',
  RESET_SOCKET: 'RESET_SOCKET',
  SET_MSG: 'SET_MSG',
  RESET_MSG: 'RESET_MSG',
};

export default ActionType;